# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='exclude_field',
            field=models.IntegerField(default=2),
        ),
    ]
